### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by henrypenny** [i-lateral/silverstripe-custommenus#6]
When using composer install this package installed in my root folder instead of vendors. I'm new to Sliver Stripe so I'm not sure if this is the expected behaviour.

**Comment by mlewis-everley** [comment]
Hi Henry,

At the moment Silverstripe modules do not install into vendor. This is because historically (pre-composer) Silverstripe modules were installed in the project root and the core framework has not yet been updated to recognise the vendor folder when it builds its manifest (at least as far as I am aware).

I believe support for the vendor directory is on the roadmap for future development. Composer support was only added in 3.1 and I have only currently only built modules to support 3.1 (until 3.2 and 4 are released as stable versions).

Not sure if that makes sense?

Cheers,

Mo

**Comment by henrypenny** [comment]
Thanks for the clarification. Makes perfect sense.
